providers:
  openai:
    apiKey: "75738273b5f7485bbbe83b0d72234059.0Q7O5XuEKM8AjDNh"
    baseURL: "https://api.z.ai/api/coding/paas/v4"
    models:
      glm-5.1:
        name: GLM 5.1
  openrouter:
    apiKey: "${OPENROUTER_API_KEY}"
    baseURL: "https://openrouter.ai/api/v1"
    models:
      moonshotai/kimi-k2.6:
        name: Kimi 2.6
model:
  provider: openrouter
  name: moonshotai/kimi-k2.6
